#!/bin/bash

LATEST=https://github.com/exercism/configlet/releases/latest

OS=$(
case $(uname) in
    (Darwin*)
        echo "mac";;
    (Linux*)
        echo "linux";;
    (Windows*)
        echo "windows";;
    (MINGW*)
        echo "windows";;
    (*)
        echo "linux";;
esac)

EXT=$(
case $OS in
    (windows*)
        echo "zip";;
    (*)
        echo "tgz";;
esac)

ARCH=$(
case $(uname -m) in
    (*64*)
        echo 64bit;;
    (*686*)
        echo 32bit;;
    (*386*)
        echo 32bit;;
    (*)
        echo 64bit;;
esac)


URL=$(curl -s https://api.github.com/repos/exercism/configlet/releases/latest | awk "/browser_download/ && /$OS-$ARCH.$EXT/" | cut -d : -f 2,3 | tr -d \")

case $EXT in
    (*zip)
        curl -s --location $URL -o bin/latest-configlet.zip
        unzip bin/latest-configlet.zip -d bin/
        rm bin/latest-configlet.zip;;
    (*)
        curl -s --location $URL | tar xz -C bin/;;
esac
